export const plantsData = {
  data() {
    return {
      plants: [
        { name: 'Menta',     
            img: './../../../static/plants/Menta.jpg',
            sun: 4, 
            water: 6, 
            care: 5, 
          },
        { name: 'Alecrim',   
            img: './../../../static/plants/Alecrim.jpg',
            sun: 8, 
            water: 3, 
            care: 4, 
          },
        { name: 'Tomilho',   
            img: './../../../static/plants/Tomilho.jpg',
            sun: 7, 
            water: 4, 
            care: 3, 
          },
        { name: 'Orégano',  
            img: './../../../static/plants/Orégano.jpg', 
            sun: 4, 
            water: 6, 
            care: 5, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },

          /*DELETE*/

        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
        { name: 'Lavanda',  
            img: './../../../static/plants/Lavanda.jpg', 
            sun: 8,
            water: 3, 
            care: 4, 
          },
      ]
    }
  }
};
